topics = [
    "Certainty and scarcity in Jason Hickel's Less is More and Roberto Bolaño's 2666",
    "The commodification of time in David Graeber's Bullshit Jobs and Virginia Woolf's Mrs. Dalloway",
    "Violence and memory in Hannah Arendt's The Origins of Totalitarianism and Cormac McCarthy's Blood Meridian",
    "Truth and power in Michel Foucault's Discipline and Punish and George Orwell's 1984",
    "The construction of identity in Simone de Beauvoir's The Second Sex and Rachel Cusk's Outline trilogy",
    "Economic anxiety and social fragmentation in Timothy Snyder's On Tyranny and Denis Johnson's Jesus' Son",
    "The phenomenology of suffering in Søren Kierkegaard's Fear and Trembling and J.M. Coetzee's Disgrace",
    "Language games and meaning-making in Ludwig Wittgenstein's Philosophical Investigations and Jorge Luis Borges' Labyrinths",
    "Epistemic injustice and narrative authority in Miranda Fricker's Epistemic Injustice and Toni Morrison's Beloved",
    "The ethics of care and moral philosophy in Martha Nussbaum's The Fragility of Goodness and Jane Austen's Persuasion",
    "Technological alienation in Jürgen Habermas's Theory of Communicative Action and Ted Chiang's Stories of Your Life",
    "The politics of recognition in Charles Taylor's Sources of the Self and James Baldwin's Giovanni's Room",
    "Existential authenticity in Jean-Paul Sartre's Being and Nothingness and Karl Ove Knausgaard's My Struggle",
    "The social construction of knowledge in Bruno Latour's We Have Never Been Modern and Italo Calvino's Invisible Cities",
    "Democratic decay and institutional trust in Ivan Krastev's After Europe and Margaret Atwood's The Handmaid's Tale",
    "The paradox of choice in Daniel Kahneman's Thinking Fast and Slow and Fernando Pessoa's The Book of Disquiet",
    "Moral luck and responsibility in Bernard Williams' Moral Luck and Kazuo Ishiguro's The Remains of the Day",
    "The critique of pure reason in Immanuel Kant's Critique of Pure Reason and Thomas Pynchon's Gravity's Rainbow",
    "Post-truth and bullshit in Harry Frankfurt's On Bullshit and Percival Everett's Erasure",
    "The genealogy of morals in Friedrich Nietzsche's On the Genealogy of Morals and Oscar Wilde's The Picture of Dorian Gray",
    "Environmental ethics and deep ecology in Aldo Leopold's A Sand County Almanac and Ursula K. Le Guin's The Dispossessed",
    "The banality of evil in Hannah Arendt's Eichmann in Jerusalem and Joy Williams's The Visiting Privilege",
    "Cognitive biases and heuristics in Amos Tversky's research and Ernest Hemingway's The Sun Also Rises",
    "The problem of other minds in David Hume's Treatise on Human Nature and Haruki Murakami's Hard-Boiled Wonderland",
    "Postcolonial identity and cultural hybridity in Homi Bhabha's The Location of Culture and Zadie Smith's White Teeth",
    "The ethics of memory in Paul Ricoeur's Memory, History, Forgetting and W.G. Sebald's Austerlitz",
    "Linguistic relativism and universal grammar in Noam Chomsky's Syntactic Structures and Anne Carson's Autobiography of Red",
    "The dialectic of enlightenment in Theodor Adorno's Dialectic of Enlightenment and Franz Kafka's The Trial",
    "Feminist epistemology and situated knowledge in Donna Haraway's Situated Knowledges and Virginia Woolf's A Room of One's Own",
    "The culture of narcissism in Christopher Lasch's The Culture of Narcissism and Bret Easton Ellis's American Psycho",
    "Mechanical reproduction and aura in Walter Benjamin's The Work of Art and Don DeLillo's White Noise",
    "The society of control in Gilles Deleuze's Postscript on Societies of Control and Dave Eggers's The Circle",
    "Rational choice theory and collective action in Mancur Olson's The Logic of Collective Action and Kurt Vonnegut's Cat's Cradle",
    "The iron cage of rationality in Max Weber's The Protestant Ethic and Jennifer Egan's A Visit from the Goon Squad",
    "Biopower and biopolitics in Michel Foucault's The Birth of Biopolitics and Octavia Butler's Parable series",
    "The clash of civilizations in Samuel Huntington's The Clash of Civilizations and Salman Rushdie's The Satanic Verses",
    "Liquid modernity and social bonds in Zygmunt Bauman's Liquid Modernity and Elena Ferrante's Neapolitan Novels",
    "The end of history debate in Francis Fukuyama's The End of History and Roberto Bolaño's The Savage Detectives",
    "Moral foundations theory in Jonathan Haidt's The Righteous Mind and Harper Lee's To Kill a Mockingbird",
    "The hermeneutics of suspicion in Paul Ricoeur's Freud and Philosophy and Henry James's The Turn of the Screw",
    "Risk society and manufactured uncertainty in Ulrich Beck's Risk Society and Michael Crichton's State of Fear",
    "The structure of scientific revolutions in Thomas Kuhn's The Structure of Scientific Revolutions and Jorge Luis Borges's The Aleph",
    "Performativity and gender in Judith Butler's Gender Trouble and Virginia Woolf's Orlando",
    "The authoritarian personality in Theodor Adorno's The Authoritarian Personality and Philip Roth's The Plot Against America",
    "Mimetic desire and scapegoating in René Girard's Violence and the Sacred and Shirley Jackson's The Lottery",
    "The commodification of culture in Fredric Jameson's Postmodernism and David Foster Wallace's Infinite Jest",
    "Negative dialectics in Theodor Adorno's Negative Dialectics and Paul Celan's poetry",
    "The spectacle of society in Guy Debord's The Society of the Spectacle and Joan Didion's The White Album",
    "Orientalism and colonial discourse in Edward Said's Orientalism and E.M. Forster's A Passage to India",
    "The ethics of ambiguity in Simone de Beauvoir's The Ethics of Ambiguity and Jean Rhys's Wide Sargasso Sea",
    "Deconstruction and différance in Jacques Derrida's Of Grammatology and Donald Barthelme's short stories",
    "The prison-house of language in Fredric Jameson's The Prison-House of Language and Samuel Beckett's Waiting for Godot",
    "Disciplinary power and surveillance in Michel Foucault's Discipline and Punish and Dave Eggers's The Circle",
    "The critique of instrumental reason in Herbert Marcuse's One-Dimensional Man and Aldous Huxley's Brave New World",
    "Ressentiment and slave morality in Friedrich Nietzsche's On the Genealogy of Morals and Fyodor Dostoevsky's Notes from Underground",
    "The phenomenology of perception in Maurice Merleau-Ponty's Phenomenology of Perception and Proust's In Search of Lost Time",
    "Alienated labor and commodity fetishism in Karl Marx's Capital and Charlie Chaplin's Modern Times",
    "The culture industry in Theodor Adorno's Culture Industry and Thomas Mann's Doctor Faustus",
    "Habitus and cultural capital in Pierre Bourdieu's Distinction and Edith Wharton's The House of Mirth",
    "The archaeology of knowledge in Michel Foucault's The Archaeology of Knowledge and Umberto Eco's The Name of the Rose",
    "Communicative action and lifeworld in Jürgen Habermas's Theory of Communicative Action and Jonathan Franzen's The Corrections",
    "The sublime and the beautiful in Immanuel Kant's Critique of Judgment and Caspar David Friedrich's paintings",
    "Existential anxiety and authentic being in Martin Heidegger's Being and Time and Albert Camus's The Stranger",
    "The logic of scientific discovery in Karl Popper's The Logic of Scientific Discovery and Thomas Pynchon's Mason & Dixon",
    "Social construction of reality in Peter Berger's The Social Construction of Reality and Don DeLillo's Underworld",
    "The madness of reason in Michel Foucault's Madness and Civilization and Ken Kesey's One Flew Over the Cuckoo's Nest",
    "Genealogical method in Friedrich Nietzsche's On the Genealogy of Morals and Toni Morrison's Paradise",
    "The politics of friendship in Jacques Derrida's Politics of Friendship and Elena Ferrante's My Brilliant Friend",
    "Negative capability in John Keats's letters and Roberto Bolaño's By Night in Chile",
    "The death of the author in Roland Barthes's The Death of the Author and Italo Calvino's If on a winter's night a traveler",
    "Pastoralism and anti-pastoralism in Leo Marx's The Machine in the Garden and Cormac McCarthy's The Road",
    "The Protestant ethic in Max Weber's The Protestant Ethic and Marilynne Robinson's Gilead",
    "Ontological difference in Martin Heidegger's Being and Time and W.G. Sebald's The Rings of Saturn",
    "The culture of complaint in Robert Hughes's The Culture of Complaint and Jonathan Franzen's Freedom",
    "Moral sentiments and sympathy in Adam Smith's Theory of Moral Sentiments and George Eliot's Middlemarch",
    "The technological society in Jacques Ellul's The Technological Society and Ray Bradbury's Fahrenheit 451",
    "Panopticism and disciplinary society in Michel Foucault's Discipline and Punish and Margaret Atwood's Oryx and Crake",
    "The culture of authenticity in Charles Taylor's The Ethics of Authenticity and J.D. Salinger's The Catcher in the Rye",
    "Liquid love and human bonds in Zygmunt Bauman's Liquid Love and Richard Yates's Revolutionary Road",
    "The will to power in Friedrich Nietzsche's The Will to Power and William Faulkner's Absalom, Absalom!",
    "Postmodern condition in Jean-François Lyotard's The Postmodern Condition and Thomas Pynchon's The Crying of Lot 49",
    "The civilizing process in Norbert Elias's The Civilizing Process and Jane Austen's Pride and Prejudice",
    "Ideology and false consciousness in Karl Marx's The German Ideology and George Orwell's Animal Farm",
    "The culture of fear in Barry Glassner's The Culture of Fear and Philip K. Dick's Minority Report",
    "Emotional intelligence in Daniel Goleman's Emotional Intelligence and Ian McEwan's Atonement",
    "The lonely crowd in David Riesman's The Lonely Crowd and Richard Ford's Rock Springs",
    "Social capital and civic engagement in Robert Putnam's Bowling Alone and Richard Russo's Empire Falls",
    "The McDonaldization of society in George Ritzer's The McDonaldization of Society and Jennifer Egan's The Candy House",
    "Moral imagination in Martha Nussbaum's Poetic Justice and Charles Dickens's Hard Times",
    "The stranger and social alienation in Georg Simmel's The Stranger and Ralph Ellison's Invisible Man",
    "Cultural hegemony in Antonio Gramsci's Prison Notebooks and Chinua Achebe's Things Fall Apart",
    "The iron law of oligarchy in Robert Michels's Political Parties and Robert Penn Warren's All the King's Men",
    "Anomie and social disorganization in Émile Durkheim's Suicide and Theodore Dreiser's Sister Carrie",
    "The presentation of self in Erving Goffman's The Presentation of Self and Patricia Highsmith's The Talented Mr. Ripley",
    "Symbolic violence in Pierre Bourdieu's Masculine Domination and Zora Neale Hurston's Their Eyes Were Watching God",
    "The society of the spectacle in Guy Debord's The Society of the Spectacle and Don DeLillo's Cosmopolis",
    "Manufactured consent in Edward Herman's Manufacturing Consent and David Foster Wallace's The Pale King",
    "The end of ideology in Daniel Bell's The End of Ideology and Joan Didion's Slouching Towards Bethlehem",
    "One-dimensional thought in Herbert Marcuse's One-Dimensional Man and Kurt Vonnegut's Player Piano",
    "The culture of narcissism in Christopher Lasch's The Culture of Narcissism and Jay McInerney's Bright Lights, Big City",
    "Bowling alone and social capital in Robert Putnam's Bowling Alone and Tom Perrotta's The Leftovers",
    "The McDonaldization thesis in George Ritzer's The McDonaldization of Society and Dave Eggers's The Every",
    "Coming of age in Samoa in Margaret Mead's Coming of Age in Samoa and Jamaica Kincaid's Annie John",
    "The feminine mystique in Betty Friedan's The Feminine Mystique and Sylvia Plath's The Bell Jar",
    "Silent spring and environmental consciousness in Rachel Carson's Silent Spring and Barbara Kingsolver's Flight Behavior",
    "The other America in Michael Harrington's The Other America and John Steinbeck's The Grapes of Wrath",
    "Habits of the heart in Robert Bellah's Habits of the Heart and Wendell Berry's Hannah Coulter",
    "The culture of poverty in Oscar Lewis's Five Families and Sandra Cisneros's The House on Mango Street",
    "Tally's corner and urban ethnography in Elliot Liebow's Tally's Corner and Gloria Naylor's The Women of Brewster Place",
    "The souls of black folk in W.E.B. Du Bois's The Souls of Black Folk and James Baldwin's Go Tell It on the Mountain",
    "Middletown studies in Robert and Helen Lynd's Middletown and Sherwood Anderson's Winesburg, Ohio",
    "The lonely crowd revisited in David Riesman's The Lonely Crowd and Rick Moody's The Ice Storm",
    "The power elite in C. Wright Mills's The Power Elite and Tom Wolfe's The Bonfire of the Vanities",
    "Status anxiety in Alain de Botton's Status Anxiety and John Updike's Rabbit series",
    "The culture of complaint revisited in Robert Hughes's Culture of Complaint and Bret Easton Ellis's Less Than Zero",
    "Bowling alone in the digital age in Robert Putnam's Bowling Alone and Sherry Turkle's Alone Together",
    "The end of men in Hanna Rosin's The End of Men and Jennifer Haigh's Mrs. Kimble",
    "Coming apart in Charles Murray's Coming Apart and J.D. Vance's Hillbilly Elegy",
    "The righteous mind in Jonathan Haidt's The Righteous Mind and Marilynne Robinson's Home",
    "Thinking, fast and slow in Daniel Kahneman's Thinking, Fast and Slow and Ian McEwan's Solar",
    "The better angels of our nature in Steven Pinker's The Better Angels and Cormac McCarthy's The Counselor",
    "Sapiens and human evolution in Yuval Harari's Sapiens and Margaret Atwood's MaddAddam trilogy",
    "21 lessons for the 21st century in Yuval Harari's 21 Lessons and Dave Eggers's The Every",
]
